[[language]]
name = "typescript"
roots = ["deno.json", "package.json", "tsconfig.json"]
language-servers = ["deno"]

[language-server.deno]
command = "deno"
args = ["lsp"]
config = { enable = true, lint = true, unstable = true }
