/** Buttons from `/locales/*.ftl`. */
export const enum Label {
  StartYes = "button-start-yes",
  SettingsLanguage = "button-settings-language",
  SettingsSync = "button-settings-sync",
  BackToMainMenu = "button-back-to-main-menu",
  BackToSettings = "button-back-to-settings",
  StartHaveAccountYes = "button-start-have-account-yes",
  StartHaveAccountNo = "button-start-have-account-no",
  StartConnectTelegramYes = "button-start-connect-telegram-yes",
  StartConnectTelegramNo = "button-start-connect-telegram-no",
  StartCreateAccountYes = "button-start-create-account-yes",
  StartCreateAccountNo = "button-start-create-account-no",
  StartSchedulesYes = "button-start-schedules-yes",
  StartSchedulesNo = "button-start-schedules-no",
  MainMenuSupport = "button-main-menu-support",
  MainMenuScholarship = "button-main-menu-scholarship",
  MainMenuInformation = "button-main-menu-information",
  MainMenuSettings = "button-main-menu-settings",
  MainMenuSchedules = "button-main-menu-schedules",
}
