const enum T {
  ButtonStartYes = "button.start--yes",
  ButtonSettingsLinkAccount = "button.settings--link-account",
  ButtonSettingsUnlinkAccount = "button.settings--link-account",
  ButtonBackToMainMenu = "button.back-to-main-menu",
  ButtonBackToSettings = "button.back-to-settings",
  ButtonBackToScholarship = "button.back-to-scholarship",
  ButtonStartHaveAccountYes = "button.start--have-account--yes",
  ButtonStartHaveAccountNo = "button.start--have-account--no",
  ButtonStartConnectTelegramYes = "button.start--connect-telegram--yes",
  ButtonStartConnectTelegramNo = "button.start--connect-telegram--no",
  ButtonStartCreateAccountYes = "button.start--create-account--yes",
  ButtonStartCreateAccountNo = "button.start--create-account--no",
  ButtonStartSchedulesYes = "button.start--schedules--yes",
  ButtonStartSchedulesNo = "button.start--schedules--no",
  ButtonScholarshipSelectCourse = "button.scholarship--select-course",
  ButtonMainMenuSupport = "button.main-menu--support",
  ButtonMainMenuScholarship = "button.main-menu--scholarship",
  ButtonMainMenuInformation = "button.main-menu--information",
  ButtonMainMenuSettings = "button.main-menu--settings",
  ButtonMainMenuSchedules = "button.main-menu--schedules",
  ButtonMainMenuSport = "button.main-menu--sport",

  CommandStart = "start",

  Default = "default",
  CourseB22Plus = "course--b22-plus",
  CourseB23 = "course--b23",
  StartHaveAccount = "start--have-account",
  StartConnectTelegram = "start--connect-telegram",
  StartCreateAccount = "start--create-account",
  StartSchedules = "start--schedules",
  ScholarshipRequest = "scholarship--request",
  ScholarshipResponse = "scholarship--response",
  ScholarshipSelectCourse = "scholarship--select-course",

  Information = "information",
  Schedules = "schedules",
  Settings = "settings",
  Sport = "sport",
  Support = "support",
}

export default T;
